{{- $auth := mustMergeOverwrite (mustDeepCopy .Values) .Values.auth -}}
{{/* Persistence is handled by volumeClaimTemplates when resourceType=statefulset */}}
{{- if (and $auth.persistence.enabled (not (eq .Values.resourceType "statefulset"))) }}
  {{/* Disable persistence for aws and gcp modes */}}
  {{- if and (not (eq $auth.chartMode "aws")) (not (eq $auth.chartMode "gcp")) }}
    {{/* No need to create a PVC if we reuse an existing claim */}}
    {{- if not $auth.persistence.existingClaimName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teleport-cluster.auth.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "persistence.volumeSize is required in chart values" $auth.persistence.volumeSize }}
  storageClassName: "{{ $auth.persistence.storageClassName }}"
    {{- end }}
  {{- end }}
{{- end }}
